wso2/apim-analytics-publisher

.gitignore
README.md
component/pom.xml
component/publisher-client/pom.xml
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/DataHolder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubPublisherRunner.java
component/publisher-client/src/main/resources/log4j.properties
pom.xml

This PR Adds a client to publish static set of events to Azure resources. In this milestone client is configurable via environment variables and following environment variables are available. Please refer ReadMe for more information

Adds a client to publish static set of events to Azure resources

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/DataHolder.java
pom.xml

findbug plugin version is upgraded in this PR to fix build issues

Changes findbug plugin version and test data

---

component/pom.xml
component/publisher-client/pom.xml
pom.xml

Preparing to release 0.0.1 version

Changes version to prepare for release

---

component/pom.xml
component/publisher-client/pom.xml
pom.xml

Prepare for next development iteration

---

issue_template.md
pull_request_template.md

Adds pull request and issue template

---

features/etc/feature.properties
features/pom.xml
features/publisher-client/pom.xml
pom.xml

This PR adds the metric reporter feature. Currently it will only pack publisher jar and some common dependencies. Azure dependencies will have to be installed manually.

Adding metric reporter feature

---

features/pom.xml
features/publisher-client/pom.xml

Fix parent pom version

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/choreo/ChoreoInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/MetricReporterTestCase.java
features/publisher-client/pom.xml
pom.xml

- Adding orbit dependencies to the feature
- Update the event schemas
- Disabled config validation

Adding dependencies to the feature

---

component/publisher-client/pom.xml
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/auth/AuthClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/auth/DefaultApi.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/auth/TokenDetailsDTO.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubProducerClientFactory.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/WSO2TokenCredential.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/exception/AuthenticationException.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultAnalyticsMetricReporter.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java
features/publisher-client/pom.xml
pom.xml

- Support auth api
- Support SAS token renew

Integrate auth API and refresh capabilities 

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/AbstractMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/AbstractMetricReporter.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/MetricReporter.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/MetricSchema.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultAnalyticsMetricReporter.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultCounterMetric.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultFaultMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/log/LogMetricEventBuilder.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultFaultMetricBuilderTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultResponseMetricBuilderTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/MetricReporterTestCase.java
component/publisher-client/src/test/resources/testng.xml

Currently there is no proper validation for MetricBuilders. Validate method just check whether given set of keys are present. Purpose of the PR is to improve that to have data type validation as well.
Also this PR paves the framework to implement adding custom metric types.
Schemas are added as Map<String, Class> where String represent the key name and Class represent the key type. This notation allows us to add complex data types as well in future. For the initial implementation only two Response and Fault schemas are supported. 
Schemas will reside in a static class which MetricEventBuilders will refer and get the relevant schema.
Upon calling build() every validation will take place. Validations which were in critical path was moved inside build to reduce impact on critical path.
Valid …

Event Schema Support

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubClient.java

Fixed formatting issue

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultAnalyticsMetricReporter.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultFaultMetricBuilderTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultResponseMetricBuilderTestCase.java

- Added required schema changes
- Added debug log

Added required schema changes

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/MetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/MetricReporter.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultCounterMetric.java

Fixed doc issues

---

component/publisher-client/pom.xml
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultFaultMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultResponseMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultFaultMetricBuilderTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultResponseMetricBuilderTestCase.java
features/publisher-client/pom.xml
pom.xml

- Add API type to schemas
- Add platform to response schema

Update response and fault schema

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultFaultMetricBuilderTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultResponseMetricBuilderTestCase.java

- Add user IP to response event 
- Remove deployment ID from the event stream 
- Fixed https://github.com/wso2-enterprise/choreo-analytics-apim/issues/142
- Fixed https://github.com/wso2-enterprise/choreo-analytics-apim/issues/143

Adding schema changes

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/WSO2TokenCredential.java
findbugs-exclude.xml

- Get the token expiry from SAS token 
- Fixed https://github.com/wso2/apim-analytics-publisher/issues/35

Get the token expiry from SAS token

---

component/publisher-client/pom.xml

- export org.wso2.am.analytics.publisher.util.

Adding missing export

---

component/publisher-client/pom.xml
pom.xml

Enable jacoco coverage

---

.github/workflows/coverage.yml

Upload code coverage reports  to Codecov via a git actions workflow.

Add Codecov workflow

---

.github/workflows/coverage.yml

Add a manual trigger to the Git Actions workflow

Add a manual trigger

---

pom.xml

- Reduce expected test coverage to 40%

Reduce expected test coverage

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultResponseMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/UserAgentParser.java
findbugs-exclude.xml

Fixes https://github.com/wso2/apim-analytics-publisher/issues/45 by adding singleton parser class with caching capability. Caching is implemented using a LinkedHashMap with maximum capacity of 50 which will act in FIFO.

Adds cached UserAgentParser

---

component/publisher-client/pom.xml
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultAnalyticsMetricReporter.java

> Change access modifier of event queue to be able to extend the DefaultAnalyticsMetricReporter class.

Change access modifier of event queue of DefaultAnalyticsMetricReporter

---

component/publisher-client/pom.xml
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubProducerClientFactory.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/WSO2TokenCredential.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/AbstractMetricReporter.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/MetricReporterFactory.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultAnalyticsMetricReporter.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultChoreoFaultMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultChoreoResponseMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultCounterMetric.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultFaultMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultResponseMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/EventQueue.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/ParallelQueueWorker.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/QueueWorker.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/log/LogCounterMetric.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/UserAgentParser.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultChoreoFaultMetricBuilderTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultChoreoResponseMetricBuilderTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultFaultMetricBuilderTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultResponseMetricBuilderTestCase.java
pom.xml

>  fixes #54
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

introduce new schema to include organization_id

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultChoreoFaultMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultChoreoResponseMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultFaultMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultResponseMetricEventBuilder.java

> Change constructors of event builders to public in order to use out of the package

Change access modifiers of event builder constructors

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultResponseMetricEventBuilder.java

$Subject. This is to cater OB scenario where same builder is used to build message twice. Earlier impl gave and error when we try to do that.

Avoids message rebuilding

---

.github/workflows/coverage.yml
codecov.yml
pom.xml

This PR adds improvements to codecov plugin and jacoco plugin. Also enables the test report comments from codecov for every PR.

Add improvements to codecov and jacoco

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubClient.java

- Adding token hash in the payload in default reporter
- Fixed https://github.com/wso2-enterprise/choreo/issues/7252

Adding token hash to the payload

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/ClientStatus.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubClient.java

- Re-initialized producer when AMQP authentication error occurred
- Fixed https://github.com/wso2/apim-analytics-publisher/issues/62

Re-initialized producer when AMQP authentication error occurred

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubClient.java

Change log level to debug

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/WSO2TokenCredential.java

- Handle unrecoverable exceptions
- Fixed https://github.com/wso2/product-apim/issues/11618

Fixed re-authentication error on on-prem key expiry/revoke

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubClient.java

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Improve error handling in EventHubClient

---

component/publisher-client/pom.xml
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/AuthAPIClientTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/util/AuthAPIMockService.java
pom.xml

- Insights auth API test improvements
- fixed https://github.com/wso2-enterprise/choreo/issues/10722

Insights auth API test improvements

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/log/LogCounterMetric.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/log/LogMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/log/LogMetricReporter.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/ErrorHandlingTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/LogMetricReporterTestCase.java
pom.xml

This PR will update the existing LogMetricsReporter class to support the ELK solution. 
This logger can be enabled using the following approach,
Step 1 - Configuring the deployment.toml file.
```
[apim.analytics]
enable = true
properties."publisher.reporter.class" = "org.wso2.am.analytics.publisher.reporter.log. LogMetricReporter"
logger.reporter.level = "INFO"
```
Step 2 - Enabling Logs from `wso2am-4.x.x/repository/conf/log4j2.properties`
```
appenders = APIM_METRICS_APPENDER, .... (list of other available appenders)
```
```
appender.APIM_METRICS_APPENDER.type = RollingFile
appender.APIM_METRICS_APPENDER.name = APIM_METRICS_APPENDER
appender.APIM_METRICS_APPENDER.fileName = ${sys:carbon.home}/repository/logs/apim_metrics.log
appender.APIM_METRICS_APPENDER.filePattern = …
```

Improve Log Metrics Reporter to support ELK solution

---

component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/ErrorHandlingTestCase.java

Fix Test failure

---

component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/EventHubClientTestCase.java

Adding test cases for the following cases
- Handling unrecoverable errors in flushing thread
- Handling authentication errors in the worker thread
- Handling RESOURCE_LIMIT_EXCEEDED error in the worker thread
- Handling any AMQP exception in the worker thread
- Handling TimeoutException error in the worker thread
- Handling any other exception in the worker thread
- Handle test cases defined in here https://github.com/wso2-enterprise/choreo/issues/11450

Adding EventHub related tests

---

features/publisher-client/pom.xml

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

remove slf4j-api and slf4j-log4j12

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/UserAgentParser.java
pom.xml

This PR adds the necessary changes to upgrade `ua-parser` to `1.5.2.wso2v1`.

Upgrade ua-parser to 1.5.2.wso2v1

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/elk/ELKMetricEventBuilder.java

> This PR will populate USER_AGENT and PLATFORM properties by analytics raw USER_AGENT header

Improve analytics event publisher

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultFaultMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultResponseMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/elk/ELKMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java

Update analytics property map with ELK the latest  improvements
This will introduce the following 2 properties
```
"apiContext":"/api1/2.0.0",
"userName":"admin@carbon.super"
```

Update analytics property map with ELK the latest  improvements

---

component/pom.xml
component/publisher-client/pom.xml
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/auth/AuthClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/auth/AuthProxyUtils.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/EventHubProducerClientFactory.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/exception/HttpClientException.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/EventHubClientTestCase.java
component/publisher-client/src/test/resources/testng.xml
features/pom.xml
features/publisher-client/pom.xml
findbugs-exclude.xml
pom.xml

Improve proxy support for EventHubClient and AuthClient
Improve proxy support for EventHubClient and AuthClient
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Improve proxy support for EventHubClient and AuthClient

---

pom.xml

Fix https://github.com/wso2/api-manager/issues/1310

Upgrade gson version

---

findbugs-exclude.xml
pom.xml

$subject
Related issue: https://github.com/wso2/api-manager/issues/1310

Upgrade gson to 2.9.1

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/MoesifClientContextHolder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/moesif/MoesifReporter.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/moesif/util/MoesifMicroserviceConstants.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/retriever/MoesifKeyRetriever.java
pom.xml

In this PR, we change some variable names to more sensible names.

Variable name change

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/moesif/MoesifReporter.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/moesif/util/MoesifMicroserviceConstants.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/retriever/MoesifKeyRetriever.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/EventHubClientTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/MoesifMetricBuilderTestCase.java

Made to read FQDN of the moesif microservice from the config.

---

.gitignore
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/GenericInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultResponseMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/elk/ELKCounterMetric.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/elk/ELKMetricEventBuilder.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/elk/ELKMetricReporter.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultResponseMetricBuilderTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/util/TestUtils.java

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Fixing ELK and custom data publishing issues due to missing fields

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/GenericInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/cloud/DefaultInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultChoreoFaultMetricBuilderTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/DefaultChoreoResponseMetricBuilderTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/MoesifMetricBuilderTestCase.java

Add environmentId to choreo events
Add environmentId to choreo events

Add environmentId to choreo events

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/MoesifClient.java

Related with: https://github.com/wso2-enterprise/choreo/issues/21793
This PR will fix the below,
**Fixing the URL**
At the moment the backend url is sent instead of the gateway url. Therefore we have to fix that to publish the gateway url along with the request path given by the user. Getting the back-end url is still on discussion and for the moment a **relative path** is set to URI. 
**Fixing Company Id**
At the moment the Organization uuid is published as the Company Id. After the discussion with Moesif it is decided to keep this value **null** in order to keep it consistent with the Moesif data model. (Mail Thread: WSO2/Moesif Partnership Launch)
**Fixing User Id**
At the moment for the test traffic, the User Id is published while appending “@carbon.super” to the end. Fixed that while …

Update data published to Moesif Dashboard

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/MoesifClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/GenericInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/MoesifMetricBuilderTestCase.java

Related with: https://github.com/wso2-enterprise/choreo/issues/21887

Add support to publish Gateway URL to Moesif

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/MoesifClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/moesif/MissedEventHandler.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/retriever/MoesifKeyRetriever.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java

Related with: https://github.com/wso2-enterprise/choreo/issues/22229

Enable environment support for Choreo - Moesif integration

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/MoesifClient.java

Related with: https://github.com/wso2-enterprise/choreo/issues/22456

Resolve reporting the latency as 1000

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/retriever/MoesifKeyRetriever.java

This will update the base64 encoding
Related with: https://github.com/wso2-enterprise/choreo/issues/22503

Update Base64 encoding

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/retriever/MoesifKeyRetriever.java

Related issue: https://github.com/wso2-enterprise/choreo/issues/22503

Improve MoesifKeyRetriever to handle both http and https

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/MoesifClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/GenericInputValidator.java

$Suject
* https://github.com/wso2-enterprise/choreo/issues/24711
* https://github.com/wso2-enterprise/choreo/issues/24845

Refactoring Error Handling For Moesif Client

---

pom.xml

* https://github.com/wso2-enterprise/choreo/issues/25069

Upgrading Moesif SDK Version

---

component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/ErrorHandlingTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/EventHubClientTestCase.java

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Add additional logs to debug the intermittent test failures

---

component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/ErrorHandlingTestCase.java
component/publisher-client/src/test/java/org/wso2/am/analytics/publisher/EventHubClientTestCase.java

Fix intermittent test failures due to concurrent modification of log appender messages.

Fix intermittent test failures

---

pom.xml

Update slf4j and Gson versions

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/auth/AuthClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/auth/AuthProxyUtils.java

- Make TrustStore path and password optional

Make TrustStore path and password optional

---

component/pom.xml
component/publisher-client/pom.xml
features/pom.xml
features/publisher-client/pom.xml
pom.xml

- Changed versioned as 1.2.17.1-SNAPSHOT

Changed versioned as 1.2.17.1-SNAPSHOT

---

component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/client/SimpleMoesifClient.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/GenericInputValidator.java
component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/util/Constants.java

- When the error response-related events are published to Moesif, an error occurs, and the events do not appear as expected.
- Fix: https://github.com/wso2/api-manager/issues/4047

Fix Moesif error response publishing issue
